[language.bash]
command = "true"

[language.rust]
command = "true"

[language.javascript]
command = "true"

[language.typescript]
command = "true"

[language.html]
command = "true"

[language.ocaml]
command = "true"

[language.python]
command = "true"

[language.c]
command = "true"

[language.cpp]
command = "true"

[language.haskell]
command = "true"

[language.go]
command = "true"

[language.dart]
command = "true"

[language.ruby]
command = "true"

[language.css]
command = "true"

[language.scss]
command = "true"

[language.purescript]
command = "true"

[language.sh]
command = "true"

[language.zsh]
command = "true"
