return {
    { import = "plugins.util" },
    { import = "plugins.lsp" },
    { import = "plugins.treesitter" },
    { import = "plugins.coding" },
    -- { import = "plugins.formatter" },
    -- { import = "plugins.lint" },
    { import = "plugins.ai" },
    { import = "plugins.editing" },
    { import = "plugins.ui" },
    { import = "plugins.git" },
    { import = "plugins.dap" },
    { import = "plugins.session" },
    { import = "plugins.org" },
    { import = "plugins.colors" },
    -- { import = "plugins.colors.melange" },
    -- { import = "plugins.ui.telescope" },
}
