colors:
  primary:
    background: '#fffbef'
    foreground: '#5c6a72'
  normal:
    black:   '#5c6a72'
    red:     '#f85552'
    green:   '#8da101'
    yellow:  '#dfa000'
    blue:    '#3a94c5'
    magenta: '#df69ba'
    cyan:    '#35a77c'
    white:   '#e8e5d5'
  bright:
    black:   '#5c6a72'
    red:     '#f85552'
    green:   '#8da101'
    yellow:  '#dfa000'
    blue:    '#3a94c5'
    magenta: '#df69ba'
    cyan:    '#35a77c'
    white:   '#e8e5d5'
