[[colors.indexed_colors]]
color = "0xb15c00"
index = 16

[[colors.indexed_colors]]
color = "0xc64343"
index = 17

[colors.bright]
black = "0xa1a6c5"
blue = "0x2e7de9"
cyan = "0x007197"
green = "0x587539"
magenta = "0x9854f1"
red = "0xf52a65"
white = "0x3760bf"
yellow = "0x8c6c3e"

[colors.normal]
black = "0xe9e9ed"
blue = "0x2e7de9"
cyan = "0x007197"
green = "0x587539"
magenta = "0x9854f1"
red = "0xf52a65"
white = "0x6172b0"
yellow = "0x8c6c3e"

[colors.primary]
background = "0xe1e2e7"
foreground = "0x3760bf"
