maximized = true
tabs = false
frame = "buttonless"
title-hidden = true
# no-multigrid = true
# wsl = true
# neovim-bin = "/home/brglng/.pixi/bin/nvim"

[font]
normal = [
    # "Maple Mono NF CN",
    # "Monaspace Argon LXGW TC NF"
    # "Monaspace Xenon Noto LXGW TC NF"
    "JetBrains Noto LXGW TC NF",
    # "JetBrains Mono",
    # "Symbols Nerd Font Mono",
    # "Flog Symbols"
]
hinting = "full"
edging = "subpixelantialias"
size = 14.0

[font.features]
"Maple Mono NF CN" = [ "+calt", "+liga" ]
"Monaspace Xenon Noto LXGW TC NF" = [ "+calt", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08", "+ss09", "+ss10", "+liga" ]
"Monaspace Argon LXGW TC NF" = [ "+calt", "+ss01", "+ss02", "+ss03", "+ss04", "+ss05", "+ss06", "+ss07", "+ss08", "+ss09", "+ss10", "+liga" ]
"JetBrains Noto LXGW TC NF" = [ "+calt", "+liga" ]

[box-drawing]
mode = "native"
