#!/bin/bash

get_script_dir() {
    script="$0"
    while [ -L "$script" ]; do
        script=$(readlink "$script")
    done
    dirname "$script"
}

# Canonical CJK double-width table, shared with Vim/Neovim and WezTerm
# (lua/brglng/cell_widths.txt). Each line is a single hex codepoint or a
# `first-last` range; every entry has width 2.
CELL_TABLE="$(get_script_dir)/../../lua/brglng/cell_widths.txt"

mkdir -p "$HOME/.local/share/tmux"
CONF_FILE="$HOME/.local/share/tmux/codepoint-widths.conf"

generate() {
    {
        echo "# Generated by ${0##*/} from ${CELL_TABLE}"
        echo "# Regenerated on each tmux start; do not edit by hand."
        echo
        while IFS= read -r line || [ -n "$line" ]; do
            line=${line%%#*}                    # drop trailing comment
            line=$(printf '%s' "$line" | tr -d '[:space:]')
            [ -n "$line" ] || continue
            echo "set -sa codepoint-widths '${line}=2'"
        done < "$CELL_TABLE"
    } > "$CONF_FILE"
}

generate